codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false

ignore:
  - "examples/**/*"
  - "tests/**/*"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/test-*.js"
  - "**/demo*.js"
  - "**/refactor*.js"
  - "**/restore*.js"
  - "**/validate.js"
  - "**/compare.js"
  - "**/benchmark.js"
  - "src/cli/**"
  - "src/**/discovery.js"
  - "src/adaptive/test-base.js"
