name: Ideas
description: Share ideas for new features or improvements
labels: ["idea", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Share your ideas to improve Adaptive Tests
        We love hearing from the community about ways to make testing better!
  - type: input
    id: title
    attributes:
      label: Idea Title
      placeholder: "Support for testing React hooks"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: "Currently, testing React hooks requires..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this?
      placeholder: "Add a discover() variant that..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
    validations:
      required: false