blank_issues_enabled: false
contact_links:
  - name: Ask a question or share an idea
    url: https://github.com/anon57396/adaptive-tests/discussions/new
    about: Use GitHub Discussions for questions and open-ended conversations.
