# Example workflow for React applications
name: React App - Adaptive Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # One-line adaptive test setup!
    - name: Run Adaptive Tests
      uses: adaptive-tests-action/adaptive-tests@v1
      with:
        command: test
        coverage: true
        test-pattern: '**/*.adaptive.test.{js,jsx,ts,tsx}'

    # Auto-discover React components
    - name: Discover Components
      uses: adaptive-tests-action/adaptive-tests@v1
      with:
        command: discover
        language: javascript
        discovery-signature: |
          {
            "type": "component",
            "framework": "react",
            "hasHooks": true
          }

    # Scaffold new adaptive tests for components
    - name: Scaffold Missing Tests
      if: github.event_name == 'pull_request'
      uses: adaptive-tests-action/adaptive-tests@v1
      with:
        command: scaffold
        language: javascript