name: Adaptive Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  adaptive-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Run Adaptive Tests
      uses: ./  # Use adaptive-tests-action/adaptive-tests@v1 when published
      with:
        command: test
        coverage: true
        fail-on-missing: true

    - name: Validate Adaptive Discovery
      uses: ./
      with:
        command: validate
        fail-on-missing: true