name: JavaScript CI

on:
  push:
    branches: [ main ]
    paths:
      - 'languages/javascript/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'languages/javascript/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: languages/javascript

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: languages/javascript/package-lock.json

      - run: npm ci
      - run: npm run lint || true
      - run: npm test