name: TypeScript CI

on:
  push:
    branches: [ main ]
    paths:
      - 'languages/typescript/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'languages/typescript/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: languages/typescript

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: languages/typescript/package-lock.json

      - run: npm ci
      - run: npx tsc --noEmit || true
      - run: npm test || true