name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environments
        uses: ./.github/actions/setup-lint

      - name: Install Node dependencies
        run: npm ci

      - name: Markdown lint
        run: npm run lint:markdown

      - name: Markdown link check
        run: npm run lint:links

      - name: Install Python tooling
        run: |
          python -m pip install --upgrade pip
          pip install ./packages/adaptive-tests-py[test] black==23.9.1 ruff==0.1.13

      - name: Python format check (black)
        run: black --check packages/adaptive-tests-py/src packages/adaptive-tests-py/tests

      - name: Python lint (ruff)
        run: ruff check packages/adaptive-tests-py/src packages/adaptive-tests-py/tests

      - name: Java verify (skip tests)
        run: mvn -pl packages/adaptive-tests-java/core -DskipTests verify
