name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environments
        uses: ./.github/actions/setup-lint

      - name: Install Node dependencies
        run: npm ci

      - name: Markdown lint
        run: npm run lint:markdown

      - name: Install Python tooling
        run: |
          python -m pip install --upgrade pip
          pip install "./languages/python[test]" black==23.9.1 ruff==0.1.13

      - name: Python format check (black)
        run: black --check languages/python/src languages/python/tests

      - name: Python lint (ruff)
        run: ruff check languages/python/src languages/python/tests

      - name: Java verify (skip tests)
        run: mvn -pl languages/java/core -DskipTests verify
